name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ">=1.22.1"
      - name: Run `internal` tests
        run: |
          cd internal
          go test
      - name: Run `sourcerer` tests
        run: |
          cd sourcerer
          go test
