name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ">=1.22.1"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
      - name: Run tests
        run: go test
